apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gpu-pv
spec:
  capacity:
    storage: 100Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/test
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: accelerator
              operator: In
              values:
                - nvidia-gtx-1080ti
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-app-test
  labels:
    app: gpu-app-test
spec:
  type: NodePort
  ports:
    - name: app1-ssh
      port: 30000
      targetPort: 22
      nodePort: 30000
  selector:
    app: gpu-app-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpu-pv-claim
  labels:
    app: gpu-app-test
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: gpu-app-test
spec:
  selector:
    matchLabels:
      app: gpu-app-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gpu-app-test
    spec:
      containers:
        - image: zhongbazhu/cfm_private:base
          name: app1
          resources:
            limits:
              nvidia.com/gpu: 2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "test"
          ports:
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: app1-storage
              mountPath: /home
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: app1-storage
          persistentVolumeClaim:
            claimName: gpu-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: gpu-app-test
spec:
  selector:
    matchLabels:
      app: gpu-app-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gpu-app-test
    spec:
      containers:
        - image: zhongbazhu/cfm_private:base
          name: app2
          resources:
            limits:
              nvidia.com/gpu: 2
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "test"
          ports:
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: app2-storage
              mountPath: /home
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: app2-storage
          persistentVolumeClaim:
            claimName: gpu-pv-claim