FROM docker

# RUN apt-get update && apt-get install -y apt-utils
# RUN apt-get install -y openssh-server sudo vim nano

# COPY user.sh /usr/local/bin/user.sh
# RUN chmod +x /usr/local/bin/user.sh
# RUN /usr/local/bin/user.sh
# RUN rm /usr/local/bin/user.sh

# COPY entrypoint.sh /usr/local/bin/entrypoint.sh
# RUN chmod +x /usr/local/bin/entrypoint.sh

# EXPOSE 22
# ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
# CMD tail -f /dev/null