apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - image: docker
      name: test-container
      command: ["tail"]
      args: ["-f", "/dev/null"]
      volumeMounts:
        - mountPath: /var/run/
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        # directory location on host
        path: /var/run/
        # this field is optional
        type: Directory
